---
name: Python package

"on": [push, pull_request]

env:
  PYO3_USE_ABI3_FORWARD_COMPATIBILITY: "1"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -U "setuptools>=60" setuptools-rust
          if [[ "${{ matrix.python-version }}" == "3.14"* ]]; then
            python -m pip install -e ".[dev,testing]"
          else
            python -m pip install -e ".[dev,testing,paramiko]"
          fi
      - name: Run ruff
        run: |
          ruff check .
          ruff format --check .
      - name: Run mypy
        run: |
          python -m pip install mypy types-paramiko typing-extensions
          python -m mypy dromedary
        continue-on-error: true
      - name: Test suite
        run: |
          python -m unittest discover -s dromedary/tests -t .
        env:
          PYTHONHASHSEED: random
